---
- name: Check for existing Satellite deployment before continuing
  roles:
    - check-for-existing-satellite

- name: Configure OS
  roles:
    - hostname-and-firewall
    - etc-hosts
    - register
    - install-configure-ipa-client

- name: Install Satellite RPMs and Configure
  roles:
    - install-satellite
    - manifest
    - sync-plan
    - lazy-sync
    - lifecycle-environments
    - RHEL7-Satellite
    - EPEL-Satellite
    - ccv-RHEL7-EPEL
    - activation-keys
    - compute-resource    

#check for existing satellite. If it exists, skip only the install portion. Still perform/check the rest.
