---
- name: Check to see if Satellite is answering
  uri:
      url: "https://{{ satellite_hostname }}/api/organizations"
      user: "{{ satellite_admin_username }}"
      password: "{{ satellite_admin_password }}"
      force_basic_auth: yes
  register: satellite_is_installed
  ignore_errors: yes
  tags: satellite-exists

- name: Set the 'satellite_is_installed' variable
  set_fact:
    satellite_is_installed: "{{ False if satellite_is_installed.failed | default(False) or satellite_is_installed.status != 200 else True }}"
  tags: satellite-exists
