---
- name: Install Satellite based RPMs
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - satellite
    - satellite-clone
    - puppet-foreman_scap_client
    - ipa-client
#  when: not satellite_is_installed
  tags: install

- name: Run satellite-installer (with DHCP, TFTP, DNS)
  shell: satellite-installer -v --scenario satellite --foreman-initial-organization "{{satellite_organization}}" --foreman-initial-location "{{satellite_location}}" --foreman-admin-password "{{satellite_admin_password}}" --foreman-proxy-dns true --foreman-proxy-dns-interface "{{ satellite_nic }}" --foreman-proxy-dns-zone "{{satellite_domain}}" --foreman-proxy-dns-forwarders "{{ laptop_ip }}" --foreman-proxy-dns-reverse "{{ satellite_rdns }}" --foreman-proxy-dhcp true --foreman-proxy-dhcp-interface "{{ satellite_nic }}" --foreman-proxy-dhcp-range "{{ satellite_dhcp_range }}" --foreman-proxy-dhcp-gateway "{{ laptop_ip }}" --foreman-proxy-dhcp-nameservers "{{ satellite_ip }}" --foreman-proxy-tftp true --foreman-proxy-tftp-servername $(hostname) --foreman-proxy-puppetca true --enable-foreman-plugin-openscap --foreman-ipa-authentication=false
  tags: install

- name: Update resolv.conf to have Satellite point to itself for DNS resolution
  lineinfile:
    path: /etc/resolv.conf
    regexp: 'nameserver'
    line: 'nameserver 192.168.126.2'
    state: present
    backrefs: yes
  tags: install

- name: Foreman Template
  template:
    src: "../templates/foreman.yml.j2"
    dest: /etc/hammer/cli.modules.d/foreman.yml
    mode: 0755
  tags: install

- name: Update Domain Settings
  command: hammer domain update --name "{{satellite_domain}}" --organizations "{{satellite_organization}}" --locations "{{satellite_location}}" --dns "{{satellite_hostname}}"
  tags: install

- name: Load OpenSCAP content
  command: foreman-rake foreman_openscap:bulk_upload:default
  tags: openscap

- name: Download Standard Policy Tailoring file from Laptop
  get_url:
    url: http://{{ laptop_ip }}/ssg-rhel7-ds-tailoring-standard-rnelson.xml
    dest: /root/ssg-rhel7-ds-tailoring-standard-rnelson.xml
    mode: 0644
    backup: yes
    force: yes
  tags: openscap
