---
- name: Install Satellite based RPMs
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - satellite
    - satellite-clone
    - puppet-foreman_scap_client
    - ipa-client
#  when: not satellite_is_installed
  tags: install

- name: Foreman Template
  template:
    src: "../templates/foreman.yml.j2"
    dest: /etc/hammer/cli.modules.d/foreman.yml
    mode: 0755
  tags: install

#- name: Scenario 1: Run satellite-installer (without DHCP, DNS, TFTP)
#  shell: satellite-installer -v --scenario satellite --foreman-initial-organization "{{satellite_organization}}" --foreman-initial-location "{{satellite_location}}" --foreman-admin-password "{{satellite_admin_password}}" --foreman-ipa-authentication=true
#  when: not satellite_is_installed
#  tags: satellite

#- name: Scenario 2: Run satellite-installer (with DHCP and TFTP, without DNS) Unable to PXE without DNS server to verify satellite.rnelson-demo.com. Possibly IdM's DNS, but did that fail? to resolve dl.fedoraproject.org while successfully resolving fedoraproject.org during the EPEL GPG key download. Need to test hosting GPG key instead of attempting to download.
#  shell: satellite-installer -v --scenario satellite --foreman-initial-organization "{{satellite_organization}}" --foreman-initial-location "{{satellite_location}}" --foreman-admin-password "{{satellite_admin_password}}" --foreman-proxy-dhcp true --foreman-proxy-dhcp-interface ens3 --foreman-proxy-dhcp-range "192.168.126.150 192.168.126.200" --foreman-proxy-dhcp-gateway 192.168.126.1 --foreman-proxy-dhcp-nameservers 192.168.126.2 --foreman-proxy-tftp true --foreman-proxy-tftp-servername "{{satellite_hostname}}" --capsule-puppet true --foreman-proxy-puppetca true --enable-foreman-plugin-openscap --foreman-ipa-authentication=true
#  when: not satellite_is_installed
#  tags: satellite

- name: Scenario 3: Run satellite-installer (with DHCP, TFTP, DNS)
  shell: satellite-installer -v --scenario satellite --foreman-initial-organization "{{satellite_organization}}" --foreman-initial-location "{{satellite_location}}" --foreman-admin-password "{{satellite_admin_password}}" --foreman-proxy-dns true --foreman-proxy-dns-interface ens3 --foreman-proxy-dns-zone "{{satellite_domain}}" --foreman-proxy-dns-forwarders 192.168.126.1 --foreman-proxy-dns-reverse 126.168.192.in-addr.arpa --foreman-proxy-dhcp true --foreman-proxy-dhcp-interface ens3 --foreman-proxy-dhcp-range "192.168.126.150 192.168.126.200" --foreman-proxy-dhcp-gateway 192.168.126.1 --foreman-proxy-dhcp-nameservers 192.168.126.2 --foreman-proxy-tftp true --foreman-proxy-tftp-servername $(hostname) --capsule-puppet true --foreman-proxy-puppetca true --enable-foreman-plugin-openscap --foreman-ipa-authentication=true
#  when: not satellite_is_installed
  tags: install

- name: Scenario 3: Update resolv.conf to have Satellite point to itself for DNS resolution
  lineinfile:
    path: /etc/resolv.conf
    regexp: 'nameserver'
    line: 'nameserver 192.168.126.2'
    state: present
    backrefs: yes
#  when: not satellite_is_installed
  tags: install

- name: Update Domain Settings
  command: hammer domain update --name "{{satellite_domain}}" --organizations "{{satellite_organization}}" --locations "{{satellite_location}}"
  tags: install

- name: Load OpenSCAP content
  command: foreman-rake foreman_openscap:bulk_upload:default
  tags: install
