---
- name: Download /etc/hosts file from Laptop
  get_url:
    url: http://{{ laptop_ip }}/hosts
    dest: /etc/hosts
    mode: 0644
    backup: yes
    force: yes
  when: not satellite_is_installed
  tags: etc-hosts
